// Code generated by mockery 2.9.0. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockPromotionRepository is an autogenerated mock type for the PromotionRepository type
type MockPromotionRepository struct {
	mock.Mock
}

// GetPromotion provides a mock function with given fields: _a0
func (_m *MockPromotionRepository) GetPromotion(_a0 string) Promotion {
	ret := _m.Called(_a0)

	var r0 Promotion
	if rf, ok := ret.Get(0).(func(string) Promotion); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Promotion)
	}

	return r0
}
